import type { Read } from '../../code-wiring'
import { parseModelFile, type RailsModel } from '../rails-schema'

const file = (...lines: string[]) => lines.join('\n')

export const FIXTURE_FILES: Record<string, string> = {
  'app/models/shift.rb': file(
    'class Shift < ApplicationRecord',
    '  include Shifts::CallbacksConcern',
    '  has_many :shift_swaps, dependent: :delete_all',
    '  has_one :badging, dependent: :nullify',
    '  before_save :set_new_default_poste',
    '  after_commit :set_weekly_option_not_up_to_date, :update_paid_leaves',
    'end',
  ),
  'app/models/concerns/shifts/callbacks_concern.rb': file(
    'module Shifts',
    '  module CallbacksConcern',
    '    extend ActiveSupport::Concern',
    '    def set_new_default_poste',
    '      Membership.find_by(user_id: user_id, shop_id: shop_id)&.update!(poste_id: poste_id)',
    '    end',
    '    def set_weekly_option_not_up_to_date',
    '      ShiftCallbackJob.perform_later(shop_id, user_id, week_start)',
    '    end',
    '    def update_paid_leaves',
    '      return unless user && starts_at',
    '      UpdatePaidLeavesCounterJob.perform_later([user.id], starts_at.to_s)',
    '    end',
    '    def run_generic_callbacks!',
    '      update_paid_leaves',
    '      set_weekly_option_not_up_to_date',
    '    end',
    '    def run_shift_callbacks!',
    '      run_callbacks(:commit) { false }',
    '      update_paid_leaves',
    '    end',
    '  end',
    'end',
  ),
  'app/models/concerns/token_authenticatable.rb': file(
    'module TokenAuthenticatable',
    '  extend ActiveSupport::Concern',
    '  included do',
    '    before_create :ensure_authentication_token',
    '  end',
    '  def ensure_authentication_token',
    '    self.authentication_token = SecureRandom.hex',
    '  end',
    'end',
  ),
  'app/models/shop.rb': file(
    'class Shop < ApplicationRecord',
    '  include TokenAuthenticatable',
    '  multisearchable against: %i[name id]',
    '  after_commit :sync_punch, on: %i[create update], if: -> { saved_change_to_name? }',
    '  before_validation :missing_method',
    '  after_save do',
    '    Organisation.where(id: organisation_id).update_all(touched_at: Time.current)',
    '  end',
    '  def sync_punch',
    '    Microservices::Punch::SettingService.new(self).call',
    '  end',
    'end',
  ),
  'app/models/organisation.rb': file('class Organisation < ApplicationRecord', '  acts_as_paranoid', 'end'),
  'app/models/membership.rb': file(
    'class Membership < ApplicationRecord',
    '  after_commit :cleanup_cache',
    '  def cleanup_cache',
    '    Rails.cache.delete(cache_key)',
    '  end',
    'end',
  ),
  'app/models/poste.rb': file('class Poste < ApplicationRecord', '  has_many :shifts, dependent: :destroy', 'end'),
  'app/models/contract.rb': file('class Contract < ApplicationRecord', '  belongs_to :user, touch: true', 'end'),
  'app/models/user.rb': file(
    'class User < ApplicationRecord',
    '  has_encrypted :bank_info',
    '  has_secure_token :api_token',
    '  def employees?',
    '    has_employees = shops.any?',
    '    has_employees',
    '  end',
    'end',
  ),
  'app/models/cluster_node.rb': file('class ClusterNode < ApplicationRecord', '  has_ancestry orphan_strategy: :adopt', 'end'),
  'app/models/night_hours_maj_slice.rb': file('class NightHoursMajSlice < ApplicationRecord', '  acts_as_list scope: %i[convention_id]', 'end'),
  'app/models/shift_swap.rb': file('class ShiftSwap < ApplicationRecord', 'end'),
  'app/models/badging.rb': file('class Badging < ApplicationRecord', 'end'),
  'app/models/predicted_shift.rb': file('class PredictedShift < ApplicationRecord', 'end'),
  'app/models/weekly_option.rb': file(
    'class WeeklyOption < ApplicationRecord',
    '  def self.upsert_employee_change!(shop_id:)',
    '    sql = sanitize_sql_array([',
    '      <<~SQL,',
    '        INSERT INTO weekly_options (shop_id, up_to_date) VALUES (?, false)',
    '        ON CONFLICT (shop_id) DO UPDATE SET up_to_date = false',
    '      SQL',
    '      shop_id',
    '    ])',
    '    connection.execute(sql)',
    '  end',
    'end',
  ),
  'app/models/paid_leaves_counter.rb': file(
    'class PaidLeavesCounter < ApplicationRecord',
    '  def self.update_days!(user, month)',
    '    where(user_id: user.id).update_all(days: 1)',
    '  end',
    'end',
  ),
  'app/jobs/shift_callback_job.rb': file(
    'class ShiftCallbackJob < ApplicationJob',
    '  def perform(shop_id, user_id, unparsed_date)',
    '    return unless Shop.find_by(id: shop_id)',
    '    WeeklyOption.upsert_employee_change!(shop_id: shop_id)',
    '  end',
    'end',
  ),
  'app/jobs/update_paid_leaves_counter_job.rb': file(
    'class UpdatePaidLeavesCounterJob < ApplicationJob',
    '  def perform(user_ids, month)',
    '    User.where(id: user_ids).each do |user|',
    '      PaidLeavesCounter.update_days!(user, month)',
    '    end',
    '  end',
    'end',
  ),
  'app/services/microservices/punch/setting_service.rb': file('class Microservices::Punch::SettingService', '  def call', '  end', 'end'),
  'app/services/v3/shifts/bulk_create_service.rb': file(
    'class V3::Shifts::BulkCreateService',
    '  def run!',
    '    Shift.import!(shifts, validate: false)',
    '    shifts.each do |shift|',
    '      shift.run_generic_callbacks!',
    '    end',
    '    @shifts_params.delete_all',
    '  end',
    'end',
  ),
  'app/controllers/api/v2/shifts_controller.rb': file(
    'class Api::V2::ShiftsController',
    '  def update',
    '    old_shift.run_shift_callbacks!',
    '  end',
    'end',
  ),
}

export const fixtureRead: Read = p => FIXTURE_FILES[p] ?? null

export const fixtureModels: RailsModel[] = Object.keys(FIXTURE_FILES)
  .filter(f => f.startsWith('app/models/') && !f.includes('/concerns/'))
  .flatMap(f => parseModelFile(f, FIXTURE_FILES[f] ?? '') ?? [])

export const FIXTURE_TABLES = [...fixtureModels.map(m => m.table), 'pg_search_documents'].sort()
